blank_issues_enabled: false
contact_links:
  - name: SPT Discord
    url: https://discord.gg/spt
    about: Get help from the SPT community
  - name: The Forge
    url: https://forge.sp-tarkov.com/mod/2470/keep-starting-gear
    about: Leave feedback on The Forge mod page
